### PR TITLE
Update Nx v13 to latest v13 and add support for Nx v16 binary package

### PR DESCRIPTION
**Pull request by rathpc**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [CONTRIBUTING.md](CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature: Add support for Nx 16+ binary package
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] Other... Please describe: Update to latest Nx v13
```

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by rathpc** [comment]
@ronnetzer any chance you would have time to review (possibly merge and release) this change?

**Comment by ronnetzer** [comment]
Hi @rathpc thanks for the contribution, I'll have some time this weekend to go over it.
Should I consider these changes to be breaking or did you keep the support of older versions?

**Comment by rathpc** [comment]
@ronnetzer this one kept support for older versions so it should be just a minor bump. I would still like to find time to update the whole project to nx16 which would indeed be a breaking change but that would be a separate much larger PR.

**Comment by rathpc** [comment]
@ronnetzer just checking in to see if you had a chance to take a look at this? It is currently blocking several downstream dependencies for me so I was hoping to get this merged soon. Thanks in advance!

**Review by ronnetzer — APPROVED** [review]

**Comment by rathpc** [comment]
Thank you!!!

**Comment by rathpc** [comment]
Is there a workflow that has to be run to get this change updated here: https://github.com/e-square-io/nx-distributed-task?

**Comment by rathpc** [comment]
I think there was some issue during that release...
https://github.com/e-square-io/nx-github-actions/actions/runs/5097529932/jobs/9164128041#step:6:308

**Comment by ronnetzer** [comment]
Thanks, noticed that too, I'll handle it today and deploy manually

**Comment by rathpc** [comment]
> Thanks, noticed that too, I'll handle it today and deploy manually

Much appreciated!!

**Comment by rathpc** [comment]
> Thanks, noticed that too, I'll handle it today and deploy manually

@ronnetzer were you able to get this deployed?

**Pull request merged**
